layouts = ["dwindle", "master"]
interval_ms = 750
icon_width = 22
icon_height = 16

[style]
foreground = "#F2F2F2"
background = "transparent"
font_family = "sans-serif"
font_size = 12.0
padding_x = 5
padding_y = 0
min_width = 0
